---
title: "Tutorial Nov 19"
author: "Jamie Duncan"
date: "19/11/2020"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(broom)
library(ggExtra)
library(knitr)
library(kableExtra)
library(texreg)
library(tidyverse)
library(stargazer)
library(corrplot)
library(jtools)

knitr::opts_chunk$set(echo = TRUE)
```


```{r}
resource <- read_rds("resource.RData")
```


```{r}
stargazer(resource)

```

```{r}

###Cor plot
resource %>%
  select(-country, -year, -regime_vdem_polcom) %>%
  drop_na() %>%
  cor() %>% corrplot::corrplot(method="number")

```

```{r}
resource %>%
  arrange(imf_divers) %>% #in a descending order
  mutate(country=factor(country, levels=country)) %>%
  ggplot(aes(y=imf_divers, x=country)) +
  geom_segment(aes(xend=country, yend=0)) + #this could be geom_bar, too
  geom_point(size=2, color="red") +
  theme_bw() + #adjust layout
  theme(axis.text.x = element_text(angle = 90, hjust=1, vjust=0.1)) + #adjust country labels
  ylab("Export Concentration Index") + xlab("Country")
```

```{r message=FALSE, warning=FALSE}
bivar <- function(iv) {
  x.var <- enquo(iv)
  plot <- ggplot(data = resource, aes(y=imf_divers, x= !! x.var)) +
  geom_point() +
  theme_bw() +
 # geom_smooth(method=lm , color="red") +
  #stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1)+
  geom_smooth(color="red") +
  ylab("Export Concentration") + xlab(x.var)
  ggMarginal(plot, type="histogram")
}
bivar(regime_vdem_supportsize)
```

```{r message=FALSE, warning=FALSE}
bivar(oil_income_p)
```

```{r}
model1 <- lm(imf_divers ~ oil_income_p + protest_gdelt + regime_vdem_supportsize + regime_capacity + debt_gdp,
   data=resource)
```

```{r}

htmlreg(model1, digits=2, stars=c(0.01, 0.05, 0.1), 
        custom.coef.names = c("Intercept", "Oil income per capita",
                              "Protest Intensity", "Support Size",
                              "Regime Capacity", "Debt % of GDP"),
        file="model1-texreg.html") 

## stargazer
stargazer(model1, out = "model1-stargazer.html",
          covariate.labels = c("Oil income per capita",
                              "Protest Intensity", "Support Size",
                              "Regime Capacity", "Debt % of GDP",
                              "Intercept"),
          dep.var.labels = "Export Concentration")
```

```{r}
summary(model1)
```

```{r}
model.coef <- coef(model1) #coefficients
model.resid <- residuals(model1) #residuals
#summary(model1)$r.squared
#summary(model1)$adj.r.squared
#summary(model1)$fstatistic
```

```{r}
model1.aug <- broom::augment(model1)

ggplot(model1.aug, aes(x=protest_gdelt, y=imf_divers)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_segment(aes(xend= protest_gdelt, yend = .fitted), alpha= .3) + #residual
  geom_point() + guides(alpha=FALSE) + #data points
  geom_point(aes(y = .fitted), shape = 2) + #predicted values
  theme_bw()
```
```{r}

model1 <- lm(imf_divers ~ oil_income_p + protest_gdelt + regime_vdem_supportsize + regime_capacity + debt_gdp,
   data=resource)
summary(model1)
```

```{r}
sd(resource$regime_vdem_supportsize)*coef(model1)[4]
```

```{r message=FALSE, warning=FALSE}
model1.pred <- predict(model1, interval = "prediction") #predicted/fitted values
model1.data <- cbind(resource, model1.pred)
model1.data
```

```{r}
pdat <- expand.grid(regime_vdem_supportsize = seq(from = min(resource$regime_vdem_supportsize), to = max(resource$regime_vdem_supportsize), by=0.001), 
                    oil_income_p = mean(resource$oil_income_p),
                    protest_gdelt = mean(resource$protest_gdelt),
                    regime_capacity = mean(resource$regime_capacity),
                    debt_gdp = mean(resource$debt_gdp))

pdat <- cbind(pdat, imf_divers = predict(model1, newdata=pdat, interval="confidence", ci.fit=T))

ggplot(pdat, mapping = aes(x=regime_vdem_supportsize, y=imf_divers.fit)) +
  geom_line(size = 2) +
  geom_ribbon(aes(ymin = imf_divers.lwr, ymax = imf_divers.upr), alpha = .25) +
  labs(x = "Support Size", y = "Predicted Export Concentration") +
  theme_bw()
```

```{r}
model2 <- lm(imf_divers ~ oil_income_p + protest_gdelt + regime_vdem_supportsize + regime_capacity + debt_gdp + regime_vdem_polcom + regime_vdem_polcom*regime_vdem_supportsize,
   data=resource)

summary(model2)
```

```{r}
ggplot(resource, aes(x=regime_vdem_supportsize, y=imf_divers, color=regime_vdem_polcom)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point()
```

```{r}
resource <- resource %>% relocate(imf_divers, .after=year)
```

```{r}
model_list <- list()
summary_list <- list()
coef <- vector()
adj_r <- vector()

```

```{r}
for(i in 4:ncol(resource)) {                 
  predictor_list <- colnames(resource)[4:i]    
  model_list[[i - 3]] <- lm(imf_divers ~ ., resource[ , c("imf_divers", predictor_list)])
  summary_list[[i - 3]] <- summary(model_list[[i-3]])
  coef[i-3] <- summary_list[[i-3]]$coefficients[2,1] #oil income per capita coefficient
  adj_r[i-3] <- summary_list[[i-3]]$adj.r.squared #pull Adj. R^2 for each model
}

texreg::htmlreg(summary_list, file="results.html")
```


```{r}
rss <- deviance(model_list[[6]]) #RSS
#sum(resid(model_list[[6]])^2) #RSS

tss <- var(resource$imf_divers)*(nrow(resource)-1) #TSS

r2 <- 1 - (rss/tss)
summary_list[[6]]$r.squared
```

```{r}
for (i  in 1:5){
  print(knitr::kable(
    anova(model_list[[i]], model_list[[i+1]])
  ))
}

library(knitr)
```

